#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 29 18:17:23 2022

@author: jiu7
"""
import numpy as np
import skimage.io as io
from utils import GraphedImage
    
tmp_dir_for_demo = '/home/jiu7/Downloads/LadderNet-master/STARE_results/im0001.png'
whole_img = io.imread(tmp_dir_for_demo)
gt, pred = whole_img[605:605*2, :], whole_img[605*2:, :]
del whole_img

graphedpred = GraphedImage(pred)
piece_list = graphedpred.piece_list
a = graphedpred.graph
print(a)
graphedpred.draw_graph()









